# Vacui.dev Mandatory Open Source License v2.0.0

Copyright (c) 2026 vacui.dev. All rights reserved.

# Preamble

This license requires that derivative works remain open. It protects contributors from patent aggression. It prohibits use in surveillance and weapons. The Author retains full rights over the Work.

If you use this software, your derivatives must be published. If you sue contributors over patents, you lose your license permanently. If you build weapons or surveillance tools with it, you were never licensed.

# Definitions

**"Work"** — the software, documentation, and other materials licensed under this agreement.

**"Author"** — the original copyright holder(s) identified in the copyright notice above.

**"Contributor"** — any person or entity that submits modifications or additions to an Author Channel.

**"Author Channel"** — any repository, distribution point, or method of code delivery that is owned, operated, or expressly designated by the Author. The Author is not required to maintain a single official repository or permanent location. Multiple Author Channels may exist simultaneously. A channel is presumed to be an Author Channel only if it is clearly identified as such by the Author (e.g., by domain ownership, account ownership, or explicit designation in the Work's documentation). Contributors who maintain independent copies are encouraged to clearly mark them as forks; however, an unmarked copy is not presumed to be an Author Channel absent affirmative evidence of Author ownership or designation.

**"You"** — the individual or entity exercising rights under this license. For purposes of all obligations, thresholds, and time periods in this license, "You" includes all entities under common control, where "common control" means direct or indirect ownership of more than 50% of voting interests, or the power to direct management and policies. Any entity that commissions, directs, or materially benefits from another party's use of the Work is jointly bound by the terms of this license.

**"Derivative Work"** — any work incorporating or based upon the Work, including modified source code, compiled binaries, and applications embedding the Work or requiring the Work to function. An AI model is a Derivative Work if it is trained on, fine-tuned on, or trained on data derived from or generated by processing the Work's source code, or on datasets that are themselves Derivative Works. Systematic or bulk generation of outputs from the Work for the purpose of creating training datasets, knowledge bases, or any resource that substitutes for direct use of the Work constitutes creation of a Derivative Work. Incidental AI model outputs produced through ordinary interactive use are not Derivative Works.

**"Distribute"** — to make available to any person or entity outside your household, whether by publication, deployment, sale, transfer, network access, or any other means.

**"Deploy"** — to use the Work or any Derivative Work in a production system, hosted service, or any publicly accessible environment. An environment that performs the functions of a production system — including serving live requests, processing real business data, or operating continuously for business purposes — constitutes Deployment regardless of how it is labeled. Internal staging, testing, and development environments that do not serve production functions and are accessible only to the licensee's employees or contractors do not constitute Deployment.

**"Patent Claims"** — any patent claim(s), now owned or hereafter acquired, including method, process, and apparatus claims, in any patent licensable by the grantor.

# 1. Grant of Rights

By exercising any right granted under this License — including but not limited to using, copying, modifying, distributing, or deploying the Work — You accept and agree to be bound by all terms of this License.

Subject to all terms of this License, the Author and each Contributor hereby grant You a perpetual, worldwide, non-exclusive, no-charge, royalty-free license to use, reproduce, modify, publicly display, publicly perform, and distribute the Work and Derivative Works.

# 2. Author Rights Reservation

The Author retains all rights not explicitly granted to licensees. The obligations in this license apply to You, not to the Author. Specifically:

   a) The Author is not bound by the publication, open source, or deletion requirements of this license.

   b) The Author may use, modify, sublicense, relicense, or distribute the Work or any Derivative Work under any terms, including proprietary terms. This includes the right to offer the Work under alternative or additional licenses (dual-licensing, commercial licensing, etc.) at the Author's sole discretion.

   c) The Author may incorporate Contributions into works under any license.

   d) The Author's right to relicense applies only to the Author's own copy of the Work and Contributions submitted to an Author Channel under Section 5. It does not extend to independent forks or Derivative Works created by others — those remain governed solely by this license.

# 3. Copyleft: Open Source Requirements

   a) **Publication requirement.** If You Distribute or Deploy the Work or any Derivative Work, You must make the complete corresponding source code publicly available under this same license within 30 days of first Distribution or Deployment.

   b) **What must be published:**
      - All source code of the Derivative Work, including build scripts and configuration necessary to compile and run it.
      - Model weights, training data, and training code for any AI model that constitutes a Derivative Work.
      - API specifications sufficient for interoperability.

   c) **What need not be published:**
      - Work-in-progress that has not been Distributed or Deployed.
      - Private notes, scratch files, and abandoned experiments that have not been Distributed or Deployed.
      - Incidental AI model outputs produced through ordinary interactive use of the Work.
      - Internal communications about the Work.

   d) **How to publish.** Source must be freely downloadable without registration, payment, or access restrictions, from a publicly accessible repository or URL. A good-faith link in the Derivative Work's documentation or README satisfies this requirement.

   e) **Superseded versions.** Published source for a version may be removed once a newer version that fully replaces it has been published. The source for the most recent Distributed or Deployed version must always remain available.

   f) **Internal use limitation.** Use of the Work or any Derivative Work that does not constitute Distribution or Deployment is permitted for purposes of evaluation, development, and integration for a period not exceeding 180 days from first internal use. After 180 days, You must either:
      - Distribute or Deploy the Work or Derivative Work (thereby triggering the publication requirements of this Section), or
      - Permanently cease all use of the Work and delete all copies and Derivative Works.

      The 180-day period runs from first internal use of any Derivative Work of the Work and is not reset by modification, restructuring, or replacement of the Derivative Work. Restarting internal use after cessation constitutes a continuation of the original use period, not a new evaluation. This provision does not apply to individuals using the Work for personal, non-commercial purposes within a single household; any use by or on behalf of a business entity, or any use that contributes to the development of a commercial product or service, is not personal non-commercial use.

# 4. Patent Defense

   a) **Patent grant.** The Author and each Contributor grant You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable patent license to make, use, sell, import, and otherwise transfer the Work, limited to Patent Claims necessarily infringed by their contributions.

   b) **Patent retaliation.** If You, or any entity You control or that controls You, initiate patent litigation alleging that the Work or any Contribution constitutes patent infringement:
      - All rights granted to You under this License terminate immediately.
      - This termination is irrevocable.

   c) **Corporate patent waiver.** Any entity with annual revenue or market capitalization exceeding 500 times the median annual household income of the jurisdiction in which it is incorporated, by using, modifying, or Distributing the Work, irrevocably agrees not to assert Patent Claims against any Contributor, the Author, or any user of the Work for any matter arising from the Work. Violation constitutes material breach.

   d) **Contributor indemnification.** Any licensee that initiates or funds patent claims against Contributors or the Author shall indemnify them for all damages, losses, and legal expenses arising from such claims.

# 5. Contributor License

   a) By submitting a Contribution to an Author Channel, You grant the Author a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable license to use, modify, sublicense, relicense, and distribute the Contribution for any purpose, including proprietary purposes. You represent that You have the authority to grant this license.

   b) **Forks encouraged.** Independent forks and branches of the Work are encouraged. Derivative Works not submitted to an Author Channel remain under this license (Section 3) and are subject to the same copyleft obligations as any other Derivative Work, but do not grant the Author any rights beyond those already established in Section 3. Only Contributions submitted to an Author Channel trigger the broader grant in Section 5(a).

# 6. Prohibited Uses

The following uses are prohibited and constitute immediate, automatic license termination:

   a) **Surveillance.** Using the Work in any system whose purpose or effect is identifying, tracking, profiling, or monitoring individuals or groups, whether in real-time or retrospectively. This includes facial recognition, behavioral analysis, communications monitoring, location tracking, social scoring, and predictive policing.

   b) **Weapons.** Using the Work in weapons systems, autonomous weapons, target acquisition, kill chain components, or any system designed to cause physical harm to persons.

   c) **Restricting individual liberty.** Using the Work as a component of systems whose primary function is restricting freedom of movement, freedom of expression, or freedom of association, including but not limited to: immigration enforcement, protest suppression, and political censorship.

   d) **Closed-source deployment.** Distributing or Deploying the Work or a Derivative Work without publishing the corresponding source as required by Section 3.

   e) **Patent aggression.** As specified in Section 4(b).

   For clarity: benign governmental use (public libraries, open data portals, scientific research, infrastructure management) is permitted provided it does not fall within (a), (b), or (c). Spam filtering, malware detection, and technical classification of non-personal data are permitted.

# 7. Commercial Use

Commercial use is permitted, provided:

   a) All requirements of Sections 3, 4, 5, and 6 are satisfied.

   b) The components of any product or service that incorporate or are derived from the Work must be freely available for local deployment by any person, under terms no more restrictive than this license. This requirement applies to the Work-derived components and any code necessary to build and run them, not to the entirety of a larger product in which they are embedded.

   c) Hosted services built on the Work must make their complete server-side source code available under Section 3.

# 8. Damages

   a) Parties agree that damages for non-compliance include, without limitation:
      - For publication violations (Section 3): the greater of (i) actual damages suffered by the Author and Contributors, or (ii) the gross amount of monetary gains reasonably attributable to the non-compliant use of the Work, calculated without reduction for costs.
      - For patent-related violations (Section 4): treble damages, full legal costs of affected Contributors, and disgorgement of all profits from patent assertion.
      - For surveillance or weapons violations (Section 6): all profits from the violating program or product line, plus compensatory damages to affected individuals.

   b) Willful violations — including deliberate concealment of Derivative Works, intentional circumvention of publication requirements, or continued use after license termination — are subject to additional punitive damages.

   c) These provisions do not limit other available legal remedies.

# 9. Termination

   a) This License terminates automatically upon breach of any term. Termination under Sections 4(b) and 6 is irrevocable.

   b) For breaches of Section 3 (publication requirements) that result from genuine oversight or administrative error — not from a decision, however informal, to defer, delay, or decline publication — You may cure the breach by publishing the required source within 30 days of receiving written notice from the Author, a Contributor, or any third party identifying the specific non-compliance. This cure is available only for Your first such breach. A breach is presumed deliberate if the Work or Derivative Work was Deployed or Distributed for more than 60 days without corresponding publication. Second and subsequent breaches are irrevocable regardless of intent.

   c) Upon termination: cease all use, delete all copies, and remove all Derivative Works from distribution.

# 10. Miscellaneous

   a) **Severability.** If any provision is held unenforceable, the remaining provisions continue in full force.

   b) **No trademark rights.** This license does not grant permission to use the Author's trade names, trademarks, or service marks.

   c) **Entire agreement.** This license constitutes the entire agreement between the parties regarding the Work. No oral or written modification is effective unless signed by the Author.

   d) **Governing law.** This License shall be governed by and construed in accordance with the laws of the jurisdiction identified in the copyright notice, or if none is identified, the jurisdiction in which the Author maintains primary residence at the time the Work is first published under this license. This choice of law is fixed at the time of first publication and does not change if the Author subsequently relocates.

   e) **Anti-evasion.** Any arrangement, structure, or series of transactions whose primary purpose or effect is to avoid the obligations of this license while obtaining the benefits of the Work constitutes a breach of this license.

This notice must be included in all copies or substantial portions of the Work and its Derivatives.

**THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.**

# Version IDs

The following values contain hashed representations of this file, for authentication purposes.
These values can be computed by taking this file, removing the contents of the IDs below
including brackets (eg: `[%#...%#]` -> ``), and then running the modified file through the
common hashing algorithms specified. The resulting value is encoded in Base64, not Hexadecimal.

* `[%#@<FILEHASH: SIZE:Pas,SHA256:e7wtMHETn/eOAvzDRio5vXjQRZWFnyxsceB0fuKK01Y >@%#]`
* `[%#@<FILEHASH: SIZE:Pas,SHA3_256:mHO9j+VCaSV8jXN6mQcGSyj4BDleTQ34Bhxeg5yglSc >@%#]`
* `[%#@<FILEHASH: SHA3_512:0NHqWxD3rLEqIMbSv3cmwPFXCNLn3K6+a2PPGJ54hSkN3a07gd+Y7mfBkLL1u1WwY5b3MNZnMHBfQP0wtQbr1g >@%#]`
